openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Arch Lab Example API'
  description: Auth service API
servers:
  - url: http://localhost:8081
    description: Example server
paths:
  /user:
    get:
      summary: Чтение информации о пользователе
      parameters:
        - name: uuid
          description: Уникальный идентификатор пользователя
          in: query
          required: true
          schema:
            type: string
        - name: no_cache
          description: Не использовать кэш на этом запросе
          in: query
          schema:
            type: boolean
            allowEmptyValue: true

      responses:
        '200':
          description: Найденный пользователь
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        404:
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Добавление нового пользователя
      parameters:
        - name: first_name
          description: Имя пользователя
          in: query
          required: true
          schema:
            type: string
        - name: last_name
          description: Фамилия пользователя
          in: query
          required: true
          schema:
            type: string
        - name: email
          description: email пользователя
          in: query
          required: true
          schema:
            type: string
        - name: gender
          description: Mushroom
          in: query
          required: true
          schema:
            type: string
        - name: login
          description: login пользователя
          in: query
          required: true
          schema:
            type: string
        - name: password
          description: пароль пользователя
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Идентификатор, добавленного пользователя
          content:
            application/json:
              schema:
                type: integer
        404:
          description: Ошибка добавления пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /user/login:
    put:
      summary: Войти в учетную запись
      parameters:
        - name: login
          description: login пользователя
          in: query
          required: true
          schema:
            type: string
        - name: password
          description: пароль пользователя
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Token
          content:
            application/json:
              schema:
                type: string
        401:
          description: Not authentication
          content:
            application/json:
              schema:
                type: string
  /user/search:
    get:
      summary: Поиск пользователей по маске имени и фамилии
      parameters:
        - name: first_name
          description: Имя
          in: query
          required: true
          schema:
            type: string
        - name: last_name
          description: Фамилия
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The users for the provided masks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users'
        404:
          description: No user found for the provided mask
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /user/auth:
    get:
      summary: Проверка аутентификации
      parameters:
        - name: token
          description: Токен аутентификации
          in: query
          required: true
          schema:
            type:string
      responses:
        '200':
          description: User ID
          content:
            application/json:
              schema:
                type: string
        401:
          description: Not authentication
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    users:
      type: array
      items:
        $ref: '#/components/schemas/user'
    user:
      type: object
      required:
        - id
        - uuid
        - first_name
        - last_name
        - email
        - title
        - login
        - password
      properties:
        id:
          type: integer
        uuid:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        title:
          type: string
        login:
          type: string
        password:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: Сообщение о ошибке
          type: string
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
security:
  - basicAuth: []
